apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: bi-elk
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0

    #----------------------- BEGIN SECURITY AUTO CONFIGURATION -----------------------
    # Enable security features
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false

    # Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
    xpack.security.http.ssl:
      enabled: false

    # Enable encryption and mutual authentication between cluster nodes
    xpack.security.transport.ssl:
      enabled: false
    #----------------------- END SECURITY AUTO CONFIGURATION -------------------------
