apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
  namespace: bi-elk
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 40Gi  
  storageClassName: gp2-csi  
