apiVersion: v1
kind: Pod
metadata:
  name: pvc-busybox
  namespace: bi-elk
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: logstash-storage
      mountPath: /mnt/logstash  # The PVC will be mounted here in this pod
  volumes:
  - name: logstash-storage
    persistentVolumeClaim:
      claimName: logstash-pvc  # Reference the same PVC used by Logstash

